import { loadCases, escapeHtml as e, subjectLabel, gradeLabel, statusLabel, entryUrl, coverUrl } from './data.js';
const $ = selector => document.querySelector(selector);
try { $('#back-to-cases').href = `./index.html${sessionStorage.getItem('catalog-query') || ''}`; } catch { /* Optional preference. */ }
try {
  const id = new URLSearchParams(location.search).get('id');
  const item = (await loadCases()).find(item => item.key === id);
  if (!item) throw new Error('未找到这个案例。请返回案例中心，选择一个已有课件。');
  let archive;
  try { const response = await fetch('./catalog/downloads.json'); if (response.ok) archive = (await response.json())[item.key]; } catch { /* Demonstration remains available when packages are absent. */ }
  document.title = `${item.title} · 案例详情`;
  const size = archive ? `${(archive.bytes / 1024 / 1024).toFixed(2)} MB` : '';
  $('#case-detail').innerHTML = `<div class="detail-heading"><div><p class="overline">CASE STUDY / ${e(subjectLabel(item.subject))} · ${e(gradeLabel(item.grade))}</p><h1>${e(item.title)}</h1><p>${e(item.summary)}</p></div><span class="status-pill">${e(statusLabel(item.status))} · v${e(item.version)}</span></div><div class="detail-grid"><div><div class="detail-cover"><img src="${coverUrl(item)}" alt="${e(item.title)}封面，风格化示意图"><a class="preview-link" href="${entryUrl(item)}"><span>▶</span> 进入互动演示</a></div><div class="detail-tags tags">${item.interactions.map(tag => `<span>${e(tag)}</span>`).join('')}<span>本地资源 · 可离线运行</span></div><section class="detail-section"><p class="overline">LEARNING OUTCOMES</p><h2>这节课，希望学生带走什么？</h2><ul class="objectives">${item.objectives.length ? item.objectives.map((goal, i) => `<li><span>${String(i + 1).padStart(2, '0')}</span>${e(goal)}</li>`).join('') : '<li>教学目标正在完善。</li>'}</ul></section><section class="detail-section"><p class="overline">THE LEARNING JOURNEY</p><h2>从一个问题，到一次理解。</h2><div class="journey">${item.steps.map((step, i) => `<article><span>${String(i + 1).padStart(2, '0')}</span><div><h3>${e(step.title)} <small>${step.minutes} 分钟</small></h3><p>${e(step.description)}</p></div></article>`).join('') || '<p>教学流程正在设计。</p>'}</div></section><section class="detail-section"><h2>使用条件与内容说明</h2><p>${e(item.requirements)}</p><p>${e(item.textbook || '请结合实际教材与学生基础使用。')}</p><p>当前状态：${e(statusLabel(item.status))}。案例供教师试用与调整，不代表已经完成真实课堂效果评估。</p><details class="technical-details"><summary>技术与来源</summary><p>${item.libraries.map(library => `${e(library.name)} ${e(library.version)}`).join(' · ') || '原生 HTML / JavaScript'}。固定版本类库与许可证随下载包提供。</p><a href="./${item.path}/README.md">查看案例说明 ↗</a></details></section></div><aside class="download-card"><p class="overline">READY FOR YOUR CLASSROOM</p><h2>把探索带进课堂。</h2><p>先在线体验，再将完整课件带走。</p><a class="button dark" href="${entryUrl(item)}">开始互动演示 <span>↗</span></a>${archive ? `<a class="button outline" id="download-case" href="./${archive.path}" download>↓ 下载独立课件包 <small>${size}</small></a>` : '<button class="button outline" disabled>下载包尚未生成</button>'}<dl><div><dt>适用学科</dt><dd>${e(subjectLabel(item.subject))}</dd></div><div><dt>适用年级</dt><dd>${e(gradeLabel(item.grade))}</dd></div><div><dt>教学时长</dt><dd>${item.durationMinutes || '待定'} 分钟</dd></div><div><dt>使用场景</dt><dd>${e(item.scenario)}</dd></div><div><dt>交付格式</dt><dd>HTML + 资源 / ZIP</dd></div></dl><div class="package-note"><strong>下载之后，怎么打开？</strong><p>解压完整文件，安装 Node.js 20+，运行包内本地服务。无需 npm 安装，运行时无需联网。</p><code>node scripts/serve.mjs</code><small>不是直接双击 HTML；启动步骤与许可证均在包内。</small></div>${archive ? `<details class="checksum"><summary>查看文件校验信息</summary><code>SHA-256<br>${archive.sha256}</code></details>` : ''}</aside></div>`;
  $('#detail-status').hidden = true; $('#case-detail').hidden = false;
} catch (error) { $('#detail-status').textContent = error.message; $('#detail-status').classList.add('error-state'); }
